### ISSUE TITLE
Voluntário para colaborar

### ISSUE THREAD

**Issue by ubiratansoares** [nfscan/android-receipt-scan-example#1]
Olá, tudo bem? :smile: 

Eu me chamo Ubiratan, adorei a idéia desse projeto (pois eu sempre quis um app assim) e gostaria muito de ajudar na experiência Android dessa aplicação.

Me coloco à disposição, se precisar de algum dos meus contatos, só falar!

E parabéns desde já pela iniciativa! :clap:

**Comment by PauloMigAlmeida** [comment]
Olá @ubiratansoares ,

Tudo beleza contigo? Fico muito grato que tenha gostado da idéia do projeto e confesso que fico muito feliz que você tem vontade de ajudar. Afinal de contas, em um mundo open source toda a ajuda é sempre muito bem vinda, não é ? :)

Eu estava revirando meus emails aqui e percebi que já fui em uma palestra sua no GDG há algum tempo atrás. Parabéns pela sua palestra. Curti bastante.

Voltando para o projeto, eu pretendo fazer um commit de uma versão inicial deste white label que estou trabalhando até o final do dia, no máximo até sábado. Depois disso, peço que se puder de uma olhada e se sentir a vontade de alterar algo, é só mandar um pull request.

Qualquer dúvida me avisa.

Abs

**Comment by ubiratansoares** [comment]
@PauloMigAlmeida tranquilo meu velho, sem pressa de verdade.

Vamos trabalhar juntos e fazer esse $$$ chegar pra quem realmente precisa!

Aquele abraço!
